Description: Pattern with packages for h8216 configurations
Name: jolla-configuration-h8216
Requires:
- pattern:jolla-hw-adaptation-akari
- pattern:jolla-hw-adaptation-tama

- droid-config-h8216-sailfish
- droid-config-h8216-pulseaudio-settings
- droid-config-h8216-policy-settings
- droid-config-h8216-preinit-plugin
- droid-config-h8216-flashing
- droid-config-h8216-bluez5
- droid-hal-version-h8216

- sailfish-content-graphics-z@ICON_RES@

Summary: Jolla Configuration h8216

